version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: civicpulse-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: civicpulse
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: civicpulse-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysqldb:3306/civicpulse?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456
      JWT_SECRET: CivicPulseSuperSecretKeyForJWTTokenGeneration2026SecureKeyWithAtLeast256Bits
      FILE_STORAGE_PATH: uploads
    depends_on:
      - mysqldb

  frontend:
    build: ./frontend
    container_name: civicpulse-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
